# project全体に適用するGradle設定。

# IDE（Android Studioなど）の利用者へ:
# IDEで設定したGradle値は、このfileで設定した値より優先される。

# build環境の設定方法については次を参照。
# http://www.gradle.org/docs/current/userguide/build_environment.html

# daemon processに渡すJVM argument。
# memory設定を調整する場合に使用する。
# 標準値: -Xmx512m -XX:MaxMetaspaceSize=256m
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# 有効にするとGradleは試験的なparallel modeで動作する。
# project間が分離されている場合だけ使用する。詳細は次を参照。
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

# AndroidXのpackage構成により、Android OSに含まれるpackageとAPKに含まれるpackageを
# 区別しやすくする。
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true

# build対象architectureを指定するproperty。
# CLIから次のように上書きすることもできる。
# ./gradlew <task> -PreactNativeArchitectures=x86_64
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# New Architectureを有効にするproperty。
# アプリでTurboModulesとFabric rendererを使用できるようになる。
# 独自のTurboModules / Fabric componentを作る場合、またはそれらを提供するlibraryを使う場合に有効にする。
newArchEnabled=true

# Hermes JS engineの有効・無効を指定するproperty。
# falseの場合は代わりにJSCを使う。
hermesEnabled=true

# edge-to-edge表示を有効にするproperty。
# appがsystem barの背面まで描画し、没入感のあるUIを表示できる。
# ReactActivityでのみ動作し、custom Activityでは使用しない。
edgeToEdgeEnabled=true

# AGP 9に含まれるKotlin組み込み機能と新DSLを無効にする。
# AGP 10.x以降ではこの無効化設定は削除される。
android.builtInKotlin=false
android.newDsl=false
