[package]
name = "symbol-nem-wallet-core-wasm"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "WASM binding for symbol-nem-wallet-core"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
getrandom = { version = "0.3.4", features = ["wasm_js"] }
js-sys = "0.3.77"
symbol-nem-wallet-core = { path = "../core" }
uuid = { version = "1.18.1", default-features = false }
wasm-bindgen = "0.2.105"
zeroize = "1.8.2"

[dev-dependencies]
hex = "0.4.3"
wasm-bindgen-test = "0.3.55"
